In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/content/october_2026_prediction (1).csv')

In [4]:
df.head()

,Date,Total Leads,Total Interested,Total Not Interested,Total Converted,Instagram Leads,Instagram Interested,Instagram Not Interested,Instagram Converted,Facebook Leads,...,X Not Interested,X Converted,YouTube Leads,YouTube Interested,YouTube Not Interested,YouTube Converted,Digital Leads,Digital Interested,Digital Not Interested,Digital Converted
0,2026-10-01,81,56,24,18,22,15,7,5,21,...,2,2,8,7,1,2,11,8,3,2
1,2026-10-02,81,54,25,19,23,15,7,5,19,...,3,2,9,7,2,2,11,7,4,2
2,2026-10-03,82,55,27,18,23,15,8,5,20,...,3,2,9,7,2,2,11,7,4,2
3,2026-10-04,86,56,26,19,21,15,6,5,23,...,2,2,10,7,3,2,13,7,5,2
4,2026-10-05,80,58,22,18,22,15,7,5,19,...,3,2,9,7,2,2,11,8,3,3

In [5]:
df.shape

(31, 29)

In [6]:
df.isnull().sum()

Date                        0
Total Leads                 0
Total Interested            0
Total Not Interested        0
Total Converted             0
Instagram Leads             0
Instagram Interested        0
Instagram Not Interested    0
Instagram Converted         0
Facebook Leads              0
Facebook Interested         0
Facebook Not Interested     0
Facebook Converted          0
LinkedIn Leads              0
LinkedIn Interested         0
LinkedIn Not Interested     0
LinkedIn Converted          0
X Leads                     0
X Interested                0
X Not Interested            0
X Converted                 0
YouTube Leads               0
YouTube Interested          0
YouTube Not Interested      0
YouTube Converted           0
Digital Leads               0
Digital Interested          0
Digital Not Interested      0
Digital Converted           0
dtype: int64

In [7]:
df.describe()

,Total Leads,Total Interested,Total Not Interested,Total Converted,Instagram Leads,Instagram Interested,Instagram Not Interested,Instagram Converted,Facebook Leads,Facebook Interested,...,X Not Interested,X Converted,YouTube Leads,YouTube Interested,YouTube Not Interested,YouTube Converted,Digital Leads,Digital Interested,Digital Not Interested,Digital Converted
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.0,31.000000,31.0,31.000000,31.000000,...,31.000000,31.000000,31.000000,31.000000,31.000000,31.0,31.000000,31.000000,31.000000,31.000000
mean,82.612903,55.870968,25.806452,18.193548,22.064516,15.0,7.000000,5.0,20.064516,14.129032,...,2.322581,1.838710,9.096774,6.935484,2.129032,2.0,11.935484,7.516129,4.354839,2.258065
std,1.256382,1.231312,1.352020,0.703295,0.359211,0.0,0.258199,0.0,0.629046,0.427546,...,0.475191,0.373878,0.396219,0.249731,0.427546,0.0,0.771815,0.508001,0.754912,0.444803
min,80.000000,54.000000,22.000000,17.000000,21.000000,15.0,6.000000,5.0,19.000000,14.000000,...,2.000000,1.000000,8.000000,6.000000,1.000000,2.0,11.000000,7.000000,3.000000,2.000000
25%,82.000000,55.000000,25.000000,18.000000,22.000000,15.0,7.000000,5.0,20.000000,14.000000,...,2.000000,2.000000,9.000000,7.000000,2.000000,2.0,11.000000,7.000000,4.000000,2.000000
50%,83.000000,56.000000,26.000000,18.000000,22.000000,15.0,7.000000,5.0,20.000000,14.000000,...,2.000000,2.000000,9.000000,7.000000,2.000000,2.0,12.000000,8.000000,5.000000,2.000000
75%,83.000000,57.000000,27.000000,19.000000,22.000000,15.0,7.000000,5.0,20.000000,14.000000,...,3.000000,2.000000,9.000000,7.000000,2.000000,2.0,12.500000,8.000000,5.000000,2.500000
max,86.000000,59.000000,29.000000,19.000000,23.000000,15.0,8.000000,5.0,23.000000,16.000000,...,3.000000,2.000000,10.000000,7.000000,3.000000,2.0,13.000000,8.000000,5.000000,3.000000

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [9]:
X=df['Total Converted']
y=df['Total Leads']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
lr=LinearRegression()
lr.fit(X_train.values.reshape(-1,1),y_train)

LinearRegression()

In [11]:
predict=lr.predict(X_test.values.reshape(-1,1))

In [12]:
print(mean_squared_error(y_test,predict))
print(r2_score(y_test,predict))

0.42664823282253855
-0.045288170415219264